on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_contractlists:
    name: Validate contractlists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Contract List schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./contractlist.schema.json
          json_path_pattern: .*contractlist.json$